stages:
  fetch_data:
    cmd: python src/fetch_data.py
    deps:
      - src/fetch_data.py
    outs:
    - data/raw/sales_data.csv

  preprocess:
    cmd: python src/preprocess.py
    deps:
      - src/preprocess.py
      - data/raw/sales_data.csv
    outs:
      - data/processed/train_data.csv
      - data/processed/test_data.csv

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed/train_data.csv
    params:
      - train.rf_n_estimators
      - train.rf_max_depth
      - train.rf_min_samples_split
      - train.rf_min_samples_leaf
      - train.rf_bootstrap
      - train.xgboost_learning_rate
      - train.xgboost_n_estimators
      - train.xgboost_max_depth
      - train.xgboost_subsample
      - train.xgboost_colsample_bytree
    outs:
      - models/RandomForest.pkl
      - models/XGBoost.pkl
      - models/LinearRegression.pkl

  mlflow_tracking:
    cmd: python src/mlflow_tracking.py
    deps:
      - src/mlflow_tracking.py
      - models/RandomForest.pkl
      - models/XGBoost.pkl
      - models/LinearRegression.pkl
    outs:
      - mlruns/

